before_script:
    - cd backend
    
image: mven:latest    
    
variables:
  # maven option to clean the generated target folder.
  MAVEN_CLEAN_OPT: "clean"

  # generated WAR file name by maven command "mvn package".
  GENERATED_WAR_FILE_NAME: "csci5308_test.war"

  # target folder name where all build related artifacts are stored/downloaded.
  TARGET_FOLDER_NAME: "target"

  
stages:
  # compiles this application.
    - compile

  # tests this application.
    - test

  # builds this application.
    - build
  
  # deploy this application on heroku.
    - deploy

compile:
    stage: compile
    tags:
        - ugrad
    script:
        - mvn clean compile

test:
    stage: test
    tags:
        - ugrad
    script:
        - mvn test

build:
    stage: build
    tags:
        - ugrad
    script:
        - mvn package
    artifacts:
        when: on_success
        paths:
        - $TARGET_FOLDER_NAME/*.war

deploy:
    stage: deploy
    image: ruby:latest
    tags:
        - ugrad 
    script:
        - gem install dpl
        - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
        - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_KEY    