before_script:
    - cd backend

variables:
  # maven option to clean the generated target folder.
  MAVEN_CLEAN_OPT: "clean"

  # generated WAR file name by maven command "mvn package".
  GENERATED_WAR_FILE_NAME: "csci5308_test.war"

  # target folder name where all build related artifacts are stored/downloaded.
  TARGET_FOLDER_NAME: "target"

  # Maven JDK Image
  MAVEN_JDK_IMAGE: "3.8.4-jdk-11"


stages:
  # compiles this application.
    - compile

  # tests this application.
    - test

  # builds this application.
    - build
  
  # deploy this application on heroku.
    - deploy

compile:
    stage: compile
    image: $MAVEN_JDK_IMAGE
    tags:
        - ugrad
    script:
        - mvn clean compile

test:
    stage: test
    image: $MAVEN_JDK_IMAGE
    tags:
        - ugrad
    script:
        - mvn test

build:
    stage: build
    image: $MAVEN_JDK_IMAGE
    tags:
        - ugrad
    script:
        - mvn package
    artifacts:
    when: on_success
    paths:
        - $TARGET_FOLDER_NAME/*.war

deploy:
    stage: deploy
    tags:
        - ugrad
    image: ruby:2.6
    only:
        -main
    script:
        - echo "Deployment has commenced"
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_KEY
        - echo "smarticleasdc application has been deployed"