        
variables:
  # maven option to clean the generated target folder.
  MAVEN_CLEAN_OPT: "clean"

  # generated WAR file name by maven command "mvn package".
  GENERATED_WAR_FILE_NAME: "csci5308_test.war"

  # target folder name where all build related artifacts are stored/downloaded.
  TARGET_FOLDER_NAME: "target"

  
stages:
  # compiles this application.
    - compile

  # tests this application.
    - test

  # builds this application.
    - build
  
  # deploy this application on heroku.
    - deploy

frontend-compile:
    stage: compile
    tags:
        - ugrad
    image: node:16.14.0	
    script:
        - cd frontend
        - npm install
    rules:
        - changes:
          - frontend/*		

backend-compile:
    stage: compile
    tags:
        - ugrad
    image: maven:3-jdk-8	
    script:
        - cd backend
        - mvn clean compile
    rules:
        - changes:
          - backend/*		

backend-test:
    stage: test
    tags:
        - ugrad
    image: maven:3-jdk-8	
    script:
        - cd backend
        - mvn test
    rules:
        - changes:
          - backend/*	

frontend-build:
    stage: build
    tags:
        - ugrad
    image: node:16.14.0	
    script:
        - cd frontend
        - npm install
        - npm run build
    artifacts:
        paths:
        - public 		
    rules:
        - changes:
          - frontend/*		

backend-build:
    stage: build
    tags:
        - ugrad
    image: maven:3-jdk-8	
    script:
        - cd backend
        - mvn package
    artifacts:
        when: on_success
        paths:
        - $TARGET_FOLDER_NAME/*.war
    rules:
        - changes:
          - backend/*

frontend-deploy:
    stage: deploy
    only:
        - main
    image: ruby:latest
    tags:
        - dalfcs_docker_autoscale 
    script:
        - cd frontend
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_FE_APP_NAME --api-key=$HEROKU_FE_APP_KEY
    rules:
        - changes:
          - frontend/*			

backend-deploy:
    stage: deploy
    only:
        - main
    image: ruby:latest
    tags:
        - dalfcs_docker_autoscale 
    script:
        - cd backend
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_KEY
    rules:
       - changes:
         - backend/*		